### ISSUE TITLE
I'm somewhat confused about the licensing (not that I want to use the bot)

### ISSUE THREAD

**Issue by eyx092** [SoundDrout-Dev/SU#1]
I don't want to self-host the bot, but I'm confused about the licensing of the bot.

- The license states that anyone can use the source code for commercial use, given that you use the same license and copyright notice, you state any changes made to the code, disclose the source, and allow users to download a copy of the source on your host server.
- However, the read me file says that self-hosting isn't allowed.

Could someone please explain?
Thank you for the clarification!

**Comment by axisiscool** [comment]
Hey! Thank you for the question... the SU repo won't have a license on release (refer to [here](https://choosealicense.com/no-permission/) for more info on what a lack of a license means). This will effectively enforce what I say in the README file.

**Comment by eyx092** [comment]
Oh okay, thank you!
